'use strict';
/**
 * End-to-end contract of the `rosepetal` block with the REAL `rp-barcode serve` (task 2B-T7 of
 * rosepetal-barcode-sdk docs/plans/fase2/02-subfase-2B.md; protocol: 00-overview.md §3; block: §4). Every other
 * test of this package runs on the client's fake engine; this file is skipped entirely unless RP_BARCODE_ENGINE
 * points to a real binary (not the fake), so `npm test` stays green on any machine:
 *
 *   RP_BARCODE_ENGINE=/path/to/rp-barcode node --test test/e2e.test.js
 *
 * The contract is test/fixtures/index.json, generated by the CLI of the same SDK (scripts/make-fixtures.js):
 * value, symbology, identifier, orientation, checksum and corners within 1 px, first straight through the client
 * and then through the node (geometry TL, TR, BR, BL and angle, the 90° fixture, the GS1 separator, add-ons,
 * Code 39 full ASCII, upcaAsEan13), plus the budget (20 crops of 600×300, robust, in one array) and a SIGKILL
 * to the engine in the middle of an array (length and order kept, respawn). A fixture that does not match here
 * is a finding for 2A: the fixture, not this file, is the reference.
 */
const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const helper = require('node-red-node-test-helper');
const { Engine } = require('@rosepetal/barcode-engine-client');   // a private engine for the direct contract; the node uses the shared one
const rp = require('../node-red-contrib-barcode-reader/lib/rp-mapping');
const { INDEX, fixture, loadRaw, loadGray, pasteOnWhite, addonAvailable, procGone, liveChildren, readerFlow, runFlow } = require('./support');

const BIN = process.env.RP_BARCODE_ENGINE;
const HELLO_TIMEOUT_MS = 10000;
// The fake announces itself in the hello (sdk "0.2.0-fake", engineVersion "0.2.0+fake"): the one reliable mark
const isFakeHello = (hello) => /fake/i.test(String(hello.sdk)) || /\+fake$/i.test(String(hello.engineVersion));
let HELLO = null;                                                  // the real engine's hello, read once before the tests
let skipReason = 'set RP_BARCODE_ENGINE to a real rp-barcode binary (serve, protocol 1) to run the end-to-end contract';
const REAL = () => HELLO !== null;

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
const within = (a, b, tol) => Math.abs(a - b) <= tol;
const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
// The block defaults of §4.1 as decodeOptions, plus what a fixture needs (addOn read, code39FullAscii)
const decodeOptionsFor = (f) => rp.optionsFromBlock({ options: f.decodeOptions }).decodeOptions;
const rgba = (raw) => ({ width: raw.width, height: raw.height, channels: 4, colorSpace: 'RGBA' });
const ROSEPETAL = (options = {}) => [{ decoder: 'rosepetal', preprocessing: 'original', options }];
const NOT_AVAILABLE_AFTER_KILL = /^Rosepetal engine not available: engine unavailable, retry in \d+ ms \(engine exited \(signal SIGKILL\)\)\. It is restarted by a later request$/;
const unhandled = [];
process.on('unhandledRejection', (reason) => unhandled.push(reason));

rp.setEngineOptions({ helloTimeoutMs: HELLO_TIMEOUT_MS, backoff: { initialMs: 100, maxMs: 200 } });
helper.init(require.resolve('node-red'));
const barcodeNode = require('../node-red-contrib-barcode-reader/barcode.js');

// Real or fake? RP_BARCODE_ENGINE unset: skip. The fake's path: skip. Anything else must greet like a real engine
// (a broken path fails the whole file: the caller asked for the real thing). The probe's process is gone before
// the first test.
before(async () => {
    if (!BIN) return;
    if (path.resolve(BIN) === path.resolve(rp.FAKE_ENGINE)) {
        skipReason = 'RP_BARCODE_ENGINE points to the fake engine of @rosepetal/barcode-engine-client: nothing real to test';
        return;
    }
    const probe = new Engine({ helloTimeoutMs: HELLO_TIMEOUT_MS });
    const hello = await probe.start();
    await probe.stop();
    if (isFakeHello(hello)) {
        skipReason = `RP_BARCODE_ENGINE ${BIN} greets as a fake (sdk ${hello.sdk}, ${hello.engineVersion}): nothing real to test`;
        return;
    }
    HELLO = hello;
});

test('e2e: hello of the real engine (protocol 1, schema 1.0, decode/ping/shutdown, limits), engineVersion = sdk+commit, shutdown exits 0', { timeout: 30000 }, async (t) => {
    if (!REAL()) return t.skip(skipReason);
    const engine = new Engine({ helloTimeoutMs: HELLO_TIMEOUT_MS });
    const hello = await engine.start();
    const child = engine.child;                                       // taken now: a failed assertion below must not leave it alive
    try {
        t.diagnostic(`engine ${hello.engineVersion} (sdk ${hello.sdk}, schema ${hello.schema}, workers ${hello.workers}, queue ${hello.queue}) from ${BIN}`);
        assert.equal(hello.id, 0);
        assert.equal(hello.op, 'hello');
        assert.equal(hello.protocol, 1);                              // the one version this node speaks
        assert.equal(hello.schema, '1.0');                            // the symbols of index.json
        assert.match(hello.sdk, /^\d+\.\d+\.\d+/, 'sdk is a semver');
        // §3.2: engineVersion is Version.SDK + "+" + the commit rp-barcode version prints (or "+dev"). The SDK number
        // itself is not pinned here: the serve branch carries 0.1.0 until the 2A-T6 bump, 0.2.0 from then on
        assert.ok(hello.engineVersion.startsWith(`${hello.sdk}+`) && hello.engineVersion.length > hello.sdk.length + 1, hello.engineVersion);
        for (const op of ['decode', 'ping', 'shutdown']) assert.ok(hello.ops.includes(op), op);
        assert.ok(Number.isInteger(hello.workers) && hello.workers >= 1, `workers ${hello.workers}`);
        assert.ok(Number.isInteger(hello.queue) && hello.queue >= 1, `queue ${hello.queue}`);
        for (const key of ['maxHeader', 'maxPayload', 'maxSide', 'maxPixels']) assert.equal(typeof hello.limits[key], 'number', key);
        assert.ok(hello.limits.maxPayload >= 600 * 300, 'maxPayload holds a crop');
        assert.deepEqual(hello, HELLO, 'the hello is the same on every start');
        assert.deepEqual(await engine.ping(), { symbols: [], image: null, timing: null });   // answered without the queue
        assert.ok(engine.running);
    } finally {
        await engine.stop();                                          // drain, shutdown: the server exits by itself
    }
    assert.equal(child.exitCode, 0, 'shutdown → status 0');
    assert.equal(child.signalCode, null, 'no signal needed');
    assert.equal(engine.child, null);
    assert.equal(engine.pending.size, 0);
});

test('e2e: every fixture decodes straight through the client to the value, symbology, identifier, orientation, checksum and corners (±1 px) of index.json; the blank gives []; a short payload is invalid_input and the engine goes on', { timeout: 60000 }, async (t) => {
    if (!REAL()) return t.skip(skipReason);
    const engine = new Engine({ helloTimeoutMs: HELLO_TIMEOUT_MS });
    try {
        assert.equal(INDEX.fixtures.length, 14);
        for (const f of INDEX.fixtures) {
            const raw = loadRaw(f.file);
            const res = await engine.decode(rgba(raw), raw.data, decodeOptionsFor(f), { timeoutMs: 10000 });
            assert.deepEqual(res.image, { width: f.width, height: f.height }, f.file);
            assert.equal(typeof res.timing.decodeMs, 'number', `${f.file} timing`);
            assert.equal(res.symbols.length, f.symbols.length, `${f.file}: ${JSON.stringify(res.symbols.map((s) => s.value))}`);
            f.symbols.forEach((exp, i) => {
                const got = res.symbols[i];
                const where = `${f.file} symbol ${i}`;
                assert.equal(got.symbology, exp.symbology, where);
                assert.equal(got.identifier, exp.identifier, where);
                assert.equal(got.value, exp.value, where);
                assert.equal(got.orientation, exp.orientation, where);
                assert.equal(got.checksum, exp.checksum, where);
                assert.equal(got.corners.length, 4, where);
                for (let k = 0; k < 4; k++) {
                    assert.ok(within(got.corners[k].x, exp.corners[k].x, 1) && within(got.corners[k].y, exp.corners[k].y, 1),
                        `${where} corner ${k}: ${JSON.stringify(got.corners[k])} vs ${JSON.stringify(exp.corners[k])}`);
                }
                assert.ok(got.lines >= 2, `${where} lines ${got.lines}`);
                assert.ok(got.confidence > 0 && got.confidence <= 1, `${where} confidence ${got.confidence}`);
            });
        }
        // Review Focus 4 at the engine: a payload of another length is invalid_input naming the length, and the
        // server keeps serving (the node's own check in applyPreprocessing fires first; this is the engine's side)
        await assert.rejects(
            engine.decode({ width: 347, height: 68, channels: 1, colorSpace: 'GRAY' }, Buffer.alloc(10), {}),
            (err) => err instanceof rp.EngineError && err.code === 'invalid_input' && /\b10\b/.test(err.message));
        assert.ok(engine.running);
        assert.equal(engine.pending.size, 0);
        const again = loadRaw('ean13.png');
        assert.equal((await engine.decode(rgba(again), again.data, decodeOptionsFor(fixture('ean13.png')))).symbols[0].value, '4006381333931');
    } finally {
        await engine.stop();
    }
    assert.equal(engine.child, null);
});

test('e2e through the node: geometry TL,TR,BR,BL and angle, the 90° fixture, GS1 separator, add-ons, full ASCII, upcaAsEan13, effort normal, blank; the engine is logged once per node', { timeout: 120000 }, async (t) => {
    if (!REAL()) return t.skip(skipReason);
    if (!addonAvailable()) return t.skip('native addon not available (preprocessing)');
    const EAN13 = fixture('ean13.png');
    // [fixture, block options, check(payload)]: one flow load, one message, no warn, per case
    const cases = [
        ['ean13.png', {}, (out) => {
            assert.equal(out.length, 1);
            const s = out[0];
            assert.deepEqual(Object.keys(s), ['format', 'value', 'box', 'corners', 'detectedBy', 'symbology', 'identifier', 'orientation', 'lines', 'confidence', 'checksum']);
            assert.equal(s.format, 'EAN-13');
            assert.equal(s.value, '4006381333931');
            assert.deepEqual(s.detectedBy, ['rosepetal_original']);
            assert.equal(s.symbology, 'EAN13');
            assert.equal(s.identifier, ']E0');
            assert.equal(s.orientation, 0);
            assert.equal(s.checksum, 'valid');
            assert.ok(s.lines >= 2 && s.confidence > 0 && s.confidence <= 1);
            assert.ok(within(s.box.angle, 0, 0.5), `angle ${s.box.angle}`);                         // compat §4: 0 horizontal
            const exp = EAN13.symbols[0].corners;                                                    // TL, TR, BR, BL, relative
            for (let k = 0; k < 4; k++) {
                assert.ok(within(s.corners[k].x * EAN13.width, exp[k].x, 1) && within(s.corners[k].y * EAN13.height, exp[k].y, 1),
                    `corner ${k}: ${JSON.stringify(s.corners[k])} vs ${JSON.stringify(exp[k])}`);
            }
            assert.ok(within(s.box.center.x * EAN13.width, (37 + 322) / 2, 1) && within(s.box.center.y * EAN13.height, (4 + 64) / 2, 1));
            assert.ok(within(s.box.size.width * EAN13.width, 285, 2) && within(s.box.size.height * EAN13.height, 60, 2));
        }],
        ['ean13.png', { effort: 'normal' }, (out) => {                                               // the other effort is accepted and reads the clean render
            assert.equal(out.length, 1);
            assert.equal(out[0].value, '4006381333931');
            assert.equal(out[0].symbology, 'EAN13');
        }],
        ['ean13-rot90.png', {}, (out) => {
            assert.equal(out.length, 1);
            const s = out[0];
            const f = fixture('ean13-rot90.png');
            assert.equal(s.value, '4006381333931');
            assert.equal(s.orientation, 90);
            assert.ok(within(s.box.angle, -90, 1), `angle ${s.box.angle}`);                          // compat §4: -90 at orientation 90
            const exp = f.symbols[0].corners;
            for (let k = 0; k < 4; k++) {
                assert.ok(within(s.corners[k].x * f.width, exp[k].x, 1) && within(s.corners[k].y * f.height, exp[k].y, 1), `corner ${k}`);
            }
        }],
        ['gs1-128.png', {}, (out) => {
            assert.equal(out.length, 1);
            const s = out[0];
            assert.equal(s.format, 'Code128');
            assert.equal(s.identifier, ']C1');
            assert.equal(s.value, '10ABC\u001d21XYZ');                                              // Review Focus 5: the 0x1D survives end to end
            assert.equal(s.value.charCodeAt(5), 0x1d);
            assert.equal(JSON.parse(JSON.stringify(s)).value, s.value);                              // and a JSON round trip (msg to the debug sidebar)
        }],
        ['code39-fullascii.png', { code39FullAscii: true }, (out) => {
            assert.equal(out.length, 1);
            assert.equal(out[0].value, 'ab/c');
            assert.equal(out[0].identifier, ']A4');
        }],
        ['code39-fullascii.png', {}, (out) => {
            assert.equal(out.length, 1);
            assert.equal(out[0].value, '+A+B/O+C');                                                  // as printed: without the option the SDK does not expand
            assert.equal(out[0].identifier, ']A0');
        }],
        ['upca.png', { upcaAsEan13: true }, (out) => {                                               // the 1.1.3 spelling: EAN-13 with the leading 0
            assert.equal(out.length, 1);
            assert.equal(out[0].format, 'EAN-13');
            assert.equal(out[0].symbology, 'EAN13');
            assert.equal(out[0].value, '0012345678905');
            assert.equal(out[0].checksum, 'valid');
        }],
        ['upca.png', {}, (out) => {
            assert.deepEqual(out.map((s) => [s.format, s.value]), [['UPC-A', '012345678905']]);
        }],
        ['upca-addon5.png', { addOn: 'read' }, (out) => {
            assert.deepEqual(out.map((s) => [s.format, s.value, s.identifier, s.symbology]), [['UPC-A', '012345678905', ']E0', 'UPCA'], ['EAN-5', '12345', ']E2', 'UPCA']]);
            const f = fixture('upca-addon5.png');
            assert.ok(within(out[1].corners[0].x * f.width, 343, 1) && within(out[1].corners[1].x * f.width, 484, 1), 'add-on corners');
        }],
        ['upca-addon5.png', {}, (out) => {                                                           // addOn ignore (the default): the main symbol only
            assert.deepEqual(out.map((s) => [s.format, s.value]), [['UPC-A', '012345678905']]);
        }],
        ['blank.png', {}, (out) => {
            assert.deepEqual(out, []);
        }]
    ];
    const versionLine = new RegExp(`^Rosepetal engine ${escapeRe(HELLO.engineVersion)} \\(protocol 1, pid \\d+\\)$`);
    for (const [file, options, check] of cases) {
        const label = `${file} ${JSON.stringify(options)}`;
        await helper.load(barcodeNode, readerFlow(ROSEPETAL(options)));
        try {
            const n1 = helper.getNode('n1');
            const msg = await runFlow(helper, loadRaw(file), { timeoutMs: 30000 });
            assert.ok(Array.isArray(msg.payload), label);
            check(msg.payload);
            assert.equal(typeof msg.performance.reader.milliseconds, 'number', label);
            assert.equal(n1.warn.callCount, 0, `${label}: ${n1.warn.getCalls().map((c) => c.args[0]).join('\n')}`);
            assert.equal(n1.error.callCount, 0, label);
            assert.equal(n1.log.callCount, 1, label);                                               // the engine is logged once per node
            assert.match(n1.log.firstCall.args[0], versionLine, label);
            assert.ok(rp.getEngine().running, label);
        } finally {
            await helper.unload();                                                                   // close → release → stop: a fresh process per case
        }
        assert.equal(rp.getEngine().child, null, label);
    }
    // Every fixture through the node (addon preprocessing, dedup, convertToFinalFormat): the `formats` of index.json
    // are the node's names, the values and corners (±1 px) those of the symbols. The client path above proves the
    // engine; this proves the mapping end to end for the seven fixtures the cases do not cover
    for (const f of INDEX.fixtures) {
        await helper.load(barcodeNode, readerFlow(ROSEPETAL(f.decodeOptions || {})));
        try {
            const n1 = helper.getNode('n1');
            const out = (await runFlow(helper, loadRaw(f.file), { timeoutMs: 30000 })).payload;
            assert.deepEqual(out.map((s) => [s.format, s.value]), f.formats.map((fmt, i) => [fmt, f.symbols[i].value]), f.file);
            out.forEach((s, i) => {
                for (let k = 0; k < 4; k++) {
                    assert.ok(within(s.corners[k].x * f.width, f.symbols[i].corners[k].x, 1) && within(s.corners[k].y * f.height, f.symbols[i].corners[k].y, 1),
                        `${f.file} symbol ${i} corner ${k}: ${JSON.stringify(s.corners[k])} vs ${JSON.stringify(f.symbols[i].corners[k])}`);
                }
            });
            assert.equal(n1.warn.callCount, 0, `${f.file}: ${n1.warn.getCalls().map((c) => c.args[0]).join('\n')}`);
        } finally {
            await helper.unload();
        }
    }
    assert.equal(rp.getEngine().refs, 0);
});

test('e2e budget: 20 crops of 600×300 in one array, robust, through the node (target < 250 ms on the dev host, asserted < 1000 ms)', { timeout: 120000 }, async (t) => {
    if (!REAL()) return t.skip(skipReason);
    if (!addonAvailable()) return t.skip('native addon not available (preprocessing)');
    const crop = pasteOnWhite(loadGray('ean13.png'), 600, 300, 120, 110);
    const crops = Array.from({ length: 20 }, () => crop);
    await helper.load(barcodeNode, readerFlow(ROSEPETAL({ effort: 'robust' })));
    try {
        const n1 = helper.getNode('n1');
        await runFlow(helper, crops, { timeoutMs: 60000 });            // warm-up: engine start, addon, JIT
        const times = [];
        for (let round = 0; round < 3; round++) {
            const msg = await runFlow(helper, crops, { timeoutMs: 60000 });
            assert.equal(msg.payload.length, 20);
            assert.ok(msg.payload.every((r) => r.length === 1 && r[0].value === '4006381333931' && r[0].symbology === 'EAN13'),
                JSON.stringify(msg.payload.map((r) => r.map((s) => s.value))));
            const s = msg.payload[0][0];
            assert.ok(within(s.corners[0].x * 600, 120 + 37, 1) && within(s.corners[0].y * 300, 110 + 4, 1), `crop geometry ${JSON.stringify(s.corners[0])}`);
            times.push(msg.performance.reader.milliseconds);
        }
        const best = Math.min(...times);
        t.diagnostic(`20 × 600×300 robust through the node (${HELLO.engineVersion}, ${HELLO.workers} workers): ${times.join(' / ')} ms (best ${best} ms; target < 250 ms on the dev host)`);
        console.log(`e2e budget: 20 crops 600x300 robust = ${times.join(' / ')} ms`);
        assert.ok(best < 1000, `best of three ${best} ms`);
        assert.equal(n1.warn.callCount, 0, n1.warn.getCalls().map((c) => c.args[0]).join('\n'));
    } finally {
        await helper.unload();
    }
});

test('e2e: SIGKILL to the real engine in the middle of an array of 40 crops: length and order kept, the crop in flight fails, the wait gives [], the engine respawns on a new pid', { timeout: 120000 }, async (t) => {
    if (!REAL()) return t.skip(skipReason);
    if (!addonAvailable()) return t.skip('native addon not available (preprocessing)');
    const crop = pasteOnWhite(loadGray('ean13.png'), 600, 300, 120, 110);
    const crops = Array.from({ length: 40 }, () => crop);
    await helper.load(barcodeNode, readerFlow(ROSEPETAL()));
    try {
        const n1 = helper.getNode('n1');
        const engine = rp.getEngine();
        await runFlow(helper, crop, { timeoutMs: 30000 });             // engine up
        const pid1 = engine.pid;
        assert.ok(pid1 > 0);
        const firstId = engine.nextId;                                 // ids are handed out as the node writes each crop, one at a time
        const pending = runFlow(helper, crops, { timeoutMs: 60000 });
        pending.catch(() => {});                                       // if the poll below fails, its 60 s timer must not reject unhandled after the unload
        // Crops 0..4 answered, crop 5 written and in flight: the kill lands with a request pending, in the same tick
        for (const t0 = Date.now(); !(engine.nextId >= firstId + 6 && engine.pending.size > 0) && Date.now() - t0 < 20000;) await sleep(1);
        assert.ok(engine.nextId >= firstId + 6 && engine.pending.size > 0, `array in flight (ids ${engine.nextId - firstId}, pending ${engine.pending.size})`);
        process.kill(pid1, 'SIGKILL');
        const msg = await pending;
        assert.equal(msg.payload.length, 40);
        assert.ok(msg.payload.every((r) => Array.isArray(r)));
        const lengths = msg.payload.map((r) => r.length);
        const shape = lengths.join('');
        const warns = n1.warn.getCalls().map((c) => c.args[0]);
        t.diagnostic(`crops after SIGKILL: ${shape}; warns: ${JSON.stringify(warns)}`);
        // Read before the kill (five, plus what the race between the poll and the kill lets through), the crop in
        // flight and those inside the wait give [] (a reply already in the pipe when the kill lands still counts as
        // read), then the respawned engine reads the rest of the same array
        assert.match(shape, /^1{5,8}0+1*$/, shape);
        assert.ok(msg.payload.filter((r) => r.length === 1).every((r) => r[0].value === '4006381333931'));
        assert.ok(warns.length >= 1 && warns.length <= 2, warns.join('\n'));
        assert.ok(warns.every((w) => /engine exited \(signal SIGKILL\)/.test(w)), warns.join('\n'));
        if (warns.length === 2) assert.equal(warns[0], 'Block 0 (rosepetal) failed: engine exited (signal SIGKILL)');
        assert.match(warns[warns.length - 1], NOT_AVAILABLE_AFTER_KILL);   // once per outage, without the install hint
        assert.equal(n1.error.callCount, 0);
        assert.ok(procGone(pid1));
        if (shape.endsWith('1')) {                                     // the respawn happened inside the array
            assert.ok(engine.running);
            assert.notEqual(engine.pid, pid1);
        }
        // The next message reads on a new process (the wait, if still running, is 100-200 ms)
        for (const t0 = Date.now(); Date.now() < engine.retryAt && Date.now() - t0 < 5000;) await sleep(10);
        const next = await runFlow(helper, crop, { timeoutMs: 30000 });
        assert.equal(next.payload.length, 1);
        assert.equal(next.payload[0].value, '4006381333931');
        assert.ok(engine.running);
        assert.notEqual(engine.pid, pid1);
        assert.equal(n1.warn.callCount, warns.length);                 // nothing new to say
        assert.deepEqual(liveChildren(), [engine.pid]);                // one process, never two
    } finally {
        await helper.unload();
        rp.getEngine().resetBackoff();
    }
});

after(async () => {
    await sleep(50);                                                    // let the last 'close' events land
    const engine = rp.getEngine();
    // Record the evidence first, then clean up whatever a failed test left behind, and only then assert on it
    const leakedChild = engine.child !== null ? engine.pid : null;
    const refs = engine.refs;
    const pending = engine.pending.size;
    const children = liveChildren();
    await engine.stop().catch(() => {});
    for (const pid of liveChildren()) {
        try { process.kill(pid, 'SIGKILL'); } catch (_) { /* gone meanwhile */ }
    }
    assert.equal(leakedChild, null, 'the shared engine still had a child after the tests');
    assert.equal(refs, 0, 'nodes still holding the shared engine after the tests');
    assert.equal(pending, 0, 'requests still pending after the tests');
    assert.deepEqual(children, [], 'child processes still alive after the tests');
    assert.deepEqual(unhandled, [], 'unhandled rejections during the tests');
});
